name: Generate
on:
  repository_dispatch:
    types: [create-pull-request]
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:

  update-readme:
    if: github.event_name == 'pull_request'
    name: Generate markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Update markdown
        shell: pwsh
        run: |
          . "./generate ps7.ps1"
      - name: Push back to PR
        shell: pwsh
        run: |
          # Commit and push the changes back to the PR
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add --all
          git commit -m "chore: Update generated content"
          git push origin ${{ github.event.pull_request.head.ref }}
